platform :ios, '7.0' 

pod 'ALMoviePlayerController', '~> 0.3.0'
pod 'ColorUtils', '~> 1.1.1'
pod 'RestKit', '~> 0.20.0'
pod 'SDWebImage', :head
pod 'SVPulsingAnnotationView', '~> 0.3.0'
pod 'SVWebViewController', '~> 1.0'
pod 'ZBarSDK', '~> 1.3.1'
#pod 'TTTAttributedLabel', :git => 'https://github.com/jeremyanticouni/TTTAttributedLabel.git'
#pod 'TTTAttributedLabel', '~> 1.9.1'
pod 'TTTAttributedLabel', :git => 'https://github.com/jamztang/TTTAttributedLabel.git', :branch => 'longpresssupport'
pod 'CocoaLumberjack', '~> 1.8.1'
#pod 'PPSSignatureView', '~> 0.1'
pod 'Reachability', '~> 3.1'
pod 'YLMoment', '~> 0.2.0'
pod 'AFOAuth2Client', '~> 0.1'
pod 'AFHTTPRequestOperationLogger', '~> 1.0'
pod 'ApigeeiOSSDK', '~> 2.0'
pod 'APParallaxHeader', :head
pod 'RaptureXML', '~> 1.0'
pod 'MMDrawerController', '~> 0.5.6'
pod 'ZipArchive', '~> 1.2'
