platform :ios, '8.0'

pod 'ActionSheetPicker-3.0'
pod 'AFNetworking'
pod 'AFNetworkActivityLogger'
pod 'AFOAuth2Manager'
pod 'ALMoviePlayerController'
pod 'ApigeeiOSSDK'
pod 'APParallaxHeader-Width'
pod 'CocoaLumberjack'
pod 'Color-Picker-for-iOS'
pod 'ColorUtils'
pod 'JAFontAwesome'
pod 'IQKeyboardManager'
pod 'jetfire'
pod 'MMDrawerController'
pod 'RaptureXML'
pod 'Reachability'
pod 'SDWebImage'
pod 'SVPulsingAnnotationView'
pod 'SVWebViewController'
pod 'TTTAttributedLabel'
pod 'YLMoment'
pod 'ZBarSDK'
pod 'ZipArchive'
